server.port = 4032

#Database
spring.datasource.url=${DB_LIVE_URL}
spring.datasource.username=${DB_LIVE_USERNAME}
spring.datasource.password=${DB_LIVE_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

#Mail API
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Messaging Queue
spring.rabbitmq.host=${RABBITMQ_HOST_LIVE}
spring.rabbitmq.port=${RABBITMQ_PORT_LIVE}
spring.rabbitmq.username=${RABBITMQ_USERNAME_LIVE}
spring.rabbitmq.password=${RABBITMQ_PASSWORD_LIVE}
spring.rabbitmq.ssl.enabled=true