spring.config.import=optional:file:.env[.properties]    

spring.application.name=ecommerce_api
spring.profiles.active=dev

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}

#Cloudinary API
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest